//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                          - Debug Stream -                                          *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program shows use of the ROBOTC Debug Stream.  It's useful for keeping track of your code    *|
|*  from behind the scenes.                                                                           *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Nothing is needed other than the Robot.                                                     *|
|*    2)  Robot > Debug Windows > Debug Stream                                                        *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
\*-----------------------------------------------------------------------------------------------4246-*/


char izard = 'A';                               // Create char 'izard' and set it to 'A' (for AWESOME).

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
  writeDebugStream("Before for loop!\n");       /* Write a statement in the debug stream letting */
                                                /* us know where we are in the program.          */

  for(int i=0; i<50; i++)                       // Loop from i=0 to i=50, incrementing by 1 each time.
  {
    writeDebugStreamLine("%d: %c",i,izard);       /* Write the loop iteration and value of */
                                                  /* 'izard' to the debug stream (1: C)    */

    izard = izard + 2;                            // Increment 'izard' by 2 (A->C, X->Z, etc)
  }

  writeDebugStreamLine("After for loop!\n");    /* Write a statement in the debug stream letting */
}                                               /* us know where we are in the program.          */
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
