#pragma config(Sensor, in6,    ,                    sensorLineFollower)
#pragma config(Sensor, in7,    ,                    sensorLineFollower)
#pragma config(Sensor, in8,    ,                    sensorLineFollower)
#pragma config(Sensor, dgtl5,  quadEncoder,         sensorQuadEncoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//////////////////////////////////////////////////////////////////////////////////////////////
//
//                                VEX LCD and Sound Demo
//
// Short little program to demonstrate the VEX LCD and ROBOTC's sound capabilities.
//
// Normally the program plays a constant frequency tone.
//   - The VEX LCD displays the current frequency
//   - The VEX LCD left and right buttons decrease / increase the tone frequency
//   - The center button is used to cycle through and play the built-in tones. The
//     name of the tone is displayed on the LCD.
//
// Multi-tasking is also demonstrated with a second task that toggles the VEX backlight.
// The backlight is on for 150 milliseconds and off for 150 milliseconds for 20 cycles.
//
//////////////////////////////////////////////////////////////////////////////////////////////

int nFrequency = 1000;
int nLastFrequency = -1;
int nDuration  = 40;

task backlightFlasher()
{
  for (int nCycles = 0; nCycles < 20; ++nCycles)
  {
    if (nCycles < 20)
      bLCDBacklight = !bLCDBacklight;
    else
      bLCDBacklight = true;
    wait1Msec(150);
  }
  bLCDBacklight = true;
}

task main()
{
  int nCycles = 0;
  startTask(backlightFlasher);
  while (true)
  {
    displayLCDCenteredString(0, "Frequency Test");

    ++nCycles;
    if (nLCDButtons & kButtonLeft)
    {
      nFrequency -= 50;
      if (nFrequency < 50)
        nFrequency = 50;

      if (nLCDButtons & kButtonRight)                 // Toggle playback on and off
      {
        bPlaySounds = !bPlaySounds;
        while (nLCDButtons != 0)
        {}
      }
      else
        bPlaySounds = true;
    }

    else if (nLCDButtons & kButtonRight)
    {
      bPlaySounds = true;
      nFrequency += 50;
      if (nFrequency > 10000)
        nFrequency = 10000;
    }

    else if (nLCDButtons & kButtonCenter)
    {
      displayLCDPos(0, 0); displayNextLCDString("Built-in Sounds");

      clearSounds();
      while (nLCDButtons & 0x02)
      {}
      for (int nSoundType = 0; nSoundType < (int) nNumbOfSystemSounds; ++nSoundType)
      {
	      switch (nSoundType)
	      {
	      default:
	      case 0: displayLCDCenteredString(0, "Beep Beep");     playSound(soundBeepBeep);         break;
	      case 1: displayLCDCenteredString(0, "Short Blip");    playSound(soundShortBlip);        break;
	      case 2: displayLCDCenteredString(0, "Blip");          playSound(soundBlip);             break;
	      case 3: displayLCDCenteredString(0, "Down Tones");    playSound(soundDownwardTones);    break;
	      case 4: displayLCDCenteredString(0, "Low Buzz");      playSound(soundLowBuzz);          break;
	      case 5: displayLCDCenteredString(0, "Up Tones");      playSound(soundUpwardTones);      break;
	      case 6: displayLCDCenteredString(0, "Fast Up Tones"); playSound(soundFastUpwardTones);  break;
	      case 7: displayLCDCenteredString(0, "Exception");     playSound(soundException);        break;
	      }
	      while (bSoundActive)
	      {}
        wait1Msec(300);
	    }
      continue;
    }

    if (true || (nFrequency != nLastFrequency) || !bSoundActive)
    {
      playTone(nFrequency, nDuration / 10);
      nLastFrequency = nFrequency;
    }

    wait1Msec(20);

    displayLCDPos(1, 0);
    if (bPlaySounds)
      displayNextLCDString("<< Freq:99999 >>");
    else
      displayNextLCDString("<< Sound Off  >>");
    displayLCDPos(1, 8);
    displayNextLCDNumber(nFrequency, 5);
  }
}
