#pragma config(Sensor, dgtl1,  ,                    sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  ,                    sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  ,                    sensorLEDtoVCC)
#pragma config(Sensor, dgtl4,  ,                    sensorLEDtoVCC)
#pragma config(Sensor, dgtl5,  ,                    sensorLEDtoVCC)
#pragma config(Sensor, dgtl6,  ,                    sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  ,                    sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  ,                    sensorLEDtoVCC)
#pragma config(Sensor, dgtl9,  ,                    sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, ,                    sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, ,                    sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, ,                    sensorLEDtoVCC)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

tSensors index;

task main()
{
	SensorType[dgtl12] = sensorTouch;
	wait1Msec(600);
	SensorType[dgtl12] = sensorLEDtoVCC;
	wait1Msec(600);

  while (true)
  {
    for (index = dgtl1; index <= dgtl12; ++index)
      SensorValue[index] = true;
    wait1Msec(600);

    for (index = dgtl1; index <= dgtl12; ++index)
      SensorValue[index] = false;
    wait1Msec(600);
  }
}
