#pragma config(ProgramType, StandaloneWithUSBCable)
#pragma config(UART_Usage, UART1, VEX_2x16_LCD)
#pragma config(Sensor, in1,    gyro,                sensorGyro)
#pragma config(Sensor, in2,    accel,               sensorAccelerometer)
#pragma config(Sensor, in3,    ,                    sensorSONAR_cm)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

///////////////////////////////////////////////////////////////////////////////
//
//                   VEX LCD and Button Test Program
//
// This program provides a quick test of the VEX optional LCD and button add-on.
//
// The add contains a LCD display of 2 x 16 alphanumeric characters equipped
// with an optional backlight.
//
// The add-on also contains three pushbuttons for user input
//
///////////////////////////////////////////////////////////////////////////////

int nButtons;
int nCycles = 0;
int nRefreshRate;

task main()
{
	int nBase;
	int cChar;

	nRefreshRate = nLCDRefreshRate;
	bLCDBacklight = true;

	nBase = '0';
	while (true)
	{
	  nLCDRefreshRate = nRefreshRate;

		if (false)
		{
			//bLCDBacklight = !bLCDBacklight;
			for (int nPos = 0; nPos < 16; ++nPos)
			{
				cChar = nBase + nPos;
				displayLCDPos(0, nPos);
				displayNextLCDChar(cChar);
				displayLCDPos(1, nPos);
				displayNextLCDChar(cChar);
			}
			if (nBase < 'z')
			  ++nBase;
			else
			  nBase = '0';
	  }

		nButtons = nLCDButtons;
		++nCycles;

    string sTemp;

    sprintf(sTemp, "%d Cycles", nCycles);
	  clearLCDLine(0);
		displayLCDPos(0, 2);
	 // displayNextLCDNumber(nCycles);
	  //displayNextLCDString(" Cycles");
	  displayNextLCDString(sTemp);
	  displayLCDCenteredString(0, sTemp);
	  clearLCDLine(1);
		displayLCDPos(1, 4);
		displayNextLCDNumber(nCycles, 5);
		wait1Msec(20);

		nButtons = nLCDButtons;
		//wait1Msec(1500);

	}
}
