#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                        - Modifying Values -                                        *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs your robot to move forward at half power for 1.5 seconds, brake for 1      *|
|*  second, reverse for 1.5 seconds, and turn left for 0.75 seconds.  There is a two second pause at  *|
|*  the beginning of the program.                                                                     *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" mode, but may not be needed for all robot configurations.                       *|
|*    2)  Power levels that can be assigned to a motor port range from -127 (full reverse) to         *|
|*        127 (full forward).                                                                         *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor Port 2        rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor Port 3        leftMotor           VEX 3-wire module     Left side motor                   *|
\*-----------------------------------------------------------------------------------------------4246-*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	wait1Msec(2000);						  // Robot waits for 2000 milliseconds before executing program

	// Move forward at half power for 1.5 seconds
	motor[rightMotor] = 63;			  // Motor on port2 is run at half (63) power forward
	motor[leftMotor]  = 63;			  // Motor on port3 is run at half (63) power forward
	wait1Msec(1500);				      // Robot runs previous code for 1500 milliseconds before moving on

	// Brake for 1 second
	motor[rightMotor] = 0;				// Motor on port2 is run at half (63) power forward
	motor[leftMotor]  = 0;				// Motor on port3 is run at half (63) power reverse
	wait1Msec(1000);				      // Robot runs previous code for 1000 milliseconds before moving on

	// Move reverse at half power for 1.5 seconds
	motor[rightMotor] = -63;			// Motor on port2 is run at half (63) power forward
	motor[leftMotor]  = -63;			// Motor on port3 is run at half (63) power reverse
	wait1Msec(1500);				      // Robot runs previous code for 1500 milliseconds before moving on

	// Turn left at full power for 0.75 seconds
	motor[rightMotor] = 127;			// Motor on port2 is run at full (127) power forward
	motor[leftMotor]  = -127;		  // Motor on port3 is run at full (-127) power reverse
	wait1Msec(750);					      // Robot runs previous code for 750 milliseconds before moving on
}													      // Program ends, and the robot stops
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
