#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

  while(1 == 1)
  {
	  motor[leftMotor] = vexRT[Ch3] / 2;
	  motor[rightMotor] = vexRT[Ch2] / 2;
  }

}
