#pragma config(Sensor, in1,    lineTrackerLeft,     sensorLineFollower)
#pragma config(Sensor, in2,    lineTrackerCenter,   sensorLineFollower)
#pragma config(Sensor, in3,    lineTrackerRight,    sensorLineFollower)
#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  wait1Msec(5000);

  //Create and set the threshold for the Line Tracking Sensors.
  int threshold;
  threshold = 1500;

  //Loop forever.
  while(1 == 1)
  {
    //If the left sensor sees dark...
    if(SensorValue(lineTrackerLeft) > threshold)
    {
      //...counter-steer to the left.
      motor[leftMotor]  = 0;
      motor[rightMotor] = 40;
    }
    //If the center sensor sees dark...
    if(SensorValue(lineTrackerCenter) > threshold)
    {
      //...move forward.
      motor[leftMotor]  = 40;
      motor[rightMotor] = 40;
    }
    //If the right sensor sees dark...
    if(SensorValue(lineTrackerRight) > threshold)
    {
      //...counter steer to the right.
      motor[leftMotor]  = 40;
      motor[rightMotor] = 0;
    }
  }
}
