#pragma config(Sensor, dgtl1,  red,                 sensorDigitalOut)
#pragma config(Sensor, dgtl2,  yellow,              sensorDigitalOut)
#pragma config(Sensor, dgtl3,  green,               sensorDigitalOut)
#pragma config(Sensor, dgtl6,  touchSensor,         sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/******************************************************************\
|*  ROBOTC for Beginners                                          *|
|*  LED Stop Light                                                *|
|*  Note that this is a custom setup and therefore we configured  *|
|*  the sensor ports with the 'Motors and Sensors Setup' menu.    *|
\******************************************************************/


task main()
{
  robotType(none);            // We do not need a specific robot type.

  turnLEDOff(red);            // Turn the red LED OFF.
  turnLEDOff(yellow);         // Turn the yellow LED OFF.
  turnLEDOff(green);          // Turn the green LED OFF.

  turnLEDOn(red);             // Turn the red LED ON.
  untilTouch(touchSensor);    // Wait until the touch sensor is pressed in.
  turnLEDOff(red);            // Turn the red LED OFF.

  turnLEDOn(yellow);          // Turn the yellow LED ON.
  wait(0.1);                  // Wait 0.1 seconds (helps touch sensor ignore noise).
  untilRelease(touchSensor);  // Wait until the touch sensor is released.
  turnLEDOff(yellow);         // Turn the yellow LED OFF.

  turnLEDOn(green);           // Turn the green LED ON.
  wait(3.0);                  // Wait 3.0 seconds.
  turnLEDOff(green);          // Turn the green LED OFF.
}
