#pragma config(Sensor, dgtl8,  sonarSensor,         sensorSONAR_cm)
#pragma config(Motor,  port2,           leftMotor,     tmotorNormal, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                     - VEX Bad Sonar Tracking -                                     *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  Not only is this code a poor example of controling your robot with sonar (it is too jerky and     *|
|*  will probably shake your robot apart!) but it is also written in very poor style.  Avoid making   *|
|*  your programs small and confusing.  Take time to expand your program, try to only do one 'thing'  *|
|*  per line.                                                                                         *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  The Sonar Sensor should be somewhere on the FRONT of the robot, facing FORWARD.             *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]              [Name]              [Type]              [Description]                   *|
|*    Digital 5               sonarSensor         VEX Sonar Sensor    Front mounted, front facing     *|
|*    Motor - Port 2          leftMotor           VEX Motor           Left motor                      *|
|*    Motor - Port 3          rightMotor          VEX Motor           Right motor                     *|
\*-----------------------------------------------------------------------------------------------4246-*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main(){
  int speed;            // Will hold a speed for the motors.

  for(;;){              // 'for ever' (an empty for loop--clever, but ugly)

    // (if you only have on line of code below each 'if' and 'else', you don't need braces '{}' -- again, poor style)

    if(SensorValue(sonarSensor) > 20 || SensorValue(sonarSensor) < 0)       // '> 20 || < 0' tells the robot to go forward while the Sonar Sensor reads in data greater than 20cm away.
      motor[leftMotor] = motor[rightMotor] = speed = 127;                     // Read from Right to Left: '127 is assigned to 'speed' is assigned to 'rightMotor' is assigned to 'leftMotor'.'
    else if(SensorValue(sonarSensor) < 20 && SensorValue(sonarSensor) > 0)  // '< 20 && > 0' tells the robot to go backward while the Sonar Sensor reads in data less than 20 cm away.
      motor[leftMotor] = motor[rightMotor] = speed = -127;                    // Back up FULL SPEED! (to avoid collision #_# )
    else                                                                    // The object is EXACTLY 20cm away.
      motor[leftMotor] = motor[rightMotor] = speed = 0;                       // STOP! Goal reached!

    clearLCDLine(0);                                  /* Display the    */
    displayLCDPos(0,0);                               /* reading of the */
    displayNextLCDString("Sonar: ");                  /* Sonar Sensor   */
    displayNextLCDNumber(SensorValue(sonarSensor));   /* on line 0.     */

    clearLCDLine(1);                                  /* Display the    */
    displayLCDPos(1,0);                               /* current speed  */
    displayNextLCDString("Speed: ");                  /* of the motors  */
    displayNextLCDNumber(speed);                      /* on line 1.     */

    wait1Msec(100);                                   // Take 10 readings per second.
  }
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
