#pragma config(Sensor, dgtl8,  sonarSensor,         sensorSONAR_cm)
#pragma config(Motor,  port2,           leftMotor,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           rightMotor,    tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                   - VEX Smooth Sonar Tracking -                                    *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program uses the Ultrasonic sensor to detect objects, and maintain a desired distance from   *|
|*  that object.  However, with standart VEX motors, you may find it difficult to slowly creep up to  *|
|*  the object as the motors will not have enough power to move the robot.                            *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  The Sonar Sensor should be somewhere on the FRONT of the robot, facing FORWARD.             *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]              [Name]              [Type]              [Description]                   *|
|*    Digital 5               sonarSensor         VEX Sonar Sensor    Front mounted, front facing     *|
|*    Motor - Port 2          leftMotor           VEX Motor           Left motor                      *|
|*    Motor - Port 3          rightMotor          VEX Motor           Right motor                     *|
\*-----------------------------------------------------------------------------------------------4246-*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
  int speed;            // Will hold a speed for the motors.
  int sonar_value;      // Will hold the current reading of the sonar sensor.
  int distance = 25;    // Specified distance to be at 25 centimeters.

  while(true)
  {
    sonar_value = SensorValue(sonarSensor);   // Store the current reading from the Sonar Sensor to 'sonar_value'.

    clearLCDLine(0);                          /* Display the    */
    displayLCDPos(0,0);                       /* reading of the */
    displayNextLCDString("Sonar: ");          /* Sonar Sensor   */
    displayNextLCDNumber(sonar_value);        /* on line 0.     */

    if(sonar_value < 0)                       // If the object is out of range: (returns -1)
    {
      speed = 127;                            // Set 'speed' to full speed ahead!
    }
    else
    {
      speed = (sonar_value - distance)*2;     // Set 'speed' equal to the 'sonar_value' minus desired 'distance'.
    }

    clearLCDLine(1);                          /* Display the    */
    displayLCDPos(1,0);                       /* current speed  */
    displayNextLCDString("Speed: ");          /* of the motors  */
    displayNextLCDNumber(speed);              /* on line 1.     */

    motor[leftMotor]  = speed;                /* Set both the left and right */
    motor[rightMotor] = speed;                /* motors to run at 'speed'.   */

    wait1Msec(100);                           // Take 10 readings per second.
  }
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
