//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                          - Display Test -                                          *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program uses the Display functions of ROBTOC on the VEX 2.0 Cortex platform.  It is a good   *|
|*  way to test to see if your LCD screen is working properly.  It will cycle through the 256 ASCII   *|
|*  characters displayable on the VEX LCD.                                                            *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  The LCD Screen must be attached to UART Port 2.                                             *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    UART Port 2         none                VEX LCD               VEX LCD Screen                    *|
\*-----------------------------------------------------------------------------------------------4246-*/


//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
bool isPrintable(int c)
{
  if (c < 0x20)
    return false;
  if (c > 0x80)
    return false;
  return true;
}

task main()
{
  clearLCDLine(0);                    // Clear line 1 (0) of the LCD
  clearLCDLine(1);                    // Clear line 2 (1) of the LCD

  int c = 0;                          // Integer 'c' will hold the ASCII code to start from
  int l = 0;                          // Integer 'l' will hold the Line number (0/1)
  int i = 0;                          // Integer 'i' will hold the line Index number (0~15)

  displayLCDPos(l,i);                 // Set the LCD cursor to Line 'l' and Index 'i'

  bLCDBacklight = true;               // Turn on LCD Backlight

  while(true)                         // An infinite loop to keep the program running until you terminate it
  {
    while(c <= 255)                   // Run this "while" loop as long as 'c' is less than or equal to '255'
    {
      if(i > 15)                      // Reached end of line
      {
        i = 0;                        // Go to start index (0)

        if(l < 1)                     // If on line 1 (0):
        {
          l = 1;                      // Go to Line 2 (1)
          clearLCDLine(1);            // Clear LCD line 2 (1)
          bLCDBacklight = false;      // Turn off LCD Backlight
        }
        else                          // If on line 2 (1):
        {
          l = 0;                      // Go to line 1 (0)
          clearLCDLine(0);            // Clear LCD Line 1 (0)
          bLCDBacklight = true;       // Turn on LCD Backlight
        }

        displayLCDPos(l,i);           // Set the LCD cursor to Line 'l' and Index 'i'
      }

      displayNextLCDChar((char)c);    // Display the 'c' (the current char) to the LCD.
      c++;                            // Increment 'c' by 1
      c &= 0xFF;
      i++;                            // Increment index 'i' by 1

      if (isPrintable(c))
        wait1Msec(125);                 // Wait 125 milliseconds before moving on (helps the LCD refresh rate keep up)
    }
  }
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
