//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                       - Multitasking Demo -                                        *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program uses tasks to display to messages to the VEX LCD screen.                             *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  You will need to have a VEX LCD attached to UART Port 2 for this program to work.           *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    UART - Port 2       -                   VEX LCD               VEX LCD screen                    *|
\*-----------------------------------------------------------------------------------------------4246-*/


//============================================| TASK ONE |============================================
task One()
{
  while(true)
  {
    displayLCDCenteredString(0, "Task ONE: /    |");
    wait1Msec(75);
    displayLCDCenteredString(0, "Task ONE:  -   /");
    wait1Msec(75);
    displayLCDCenteredString(0, "Task ONE:   -  -");
    wait1Msec(75);
    displayLCDCenteredString(0, "Task ONE:    \ \ ");   /* An extra space is needed because '\' */
    wait1Msec(75);                                      /* is the "Line Continuation character. */
  }
}
//====================================================================================================

//============================================| TASK TWO |============================================
task Two()
{
  while(true)
  {
    displayLCDCenteredString(1, "Task TWO:    / |");
    wait1Msec(75);
    displayLCDCenteredString(1, "Task TWO:   -  \ ");   /* An extra space is needed because '\' */
    wait1Msec(75);                                      /* is the "Line Continuation character. */
    displayLCDCenteredString(1, "Task TWO:  -   -");
    wait1Msec(75);
    displayLCDCenteredString(1, "Task TWO: \    /");
    wait1Msec(75);
  }
}
//====================================================================================================


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
  startTask(One);   /* Comment out either of these two lines */
  startTask(Two);   /* to see a Task running individually.   */

  while(true)
  {
  	wait1Msec(1);
    // Keep the program alive
  }
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
